### ISSUE TITLE
No such file or directory: '/data/trained-models...'

### ISSUE THREAD

**Issue by mike-laws** [thekevinscott/ambient-music-generation#35]
When following the readme I'm unable to use the provided trained models:

I've cloned the repo, changed to the directory and executed the command:

docker run -it -v `pwd\`:/data --entrypoint python jimmywhitaker/music-transformer:0.1 generate.py --load_path=/data/trained-models/ambient-musictransformer-model-2-june-3-2020-750-epochs-more-data --inputs /data/samples/midi/1.mid --length=2048 --save_path=/data/generated-music/my-sample-song-1.mid

I get the following FileNotFoundError:

PS D:\ambient-music-generation> docker run -it -v `pwd`:/data --entrypoint python jimmywhitaker/music-transformer:0.1 generate.py --load_path=/data/trained-models/ambient-musictransformer-model-2-june-3-2020-750-epochs-more-data --inputs /data/samples/midi/1.mid --length=2048 --save_path=/data/generated-music/my-sample-song-1.mid
2022-11-10 21:32:26.830660: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcuda.so.1
2022-11-10 21:32:26.830712: E tensorflow/stream_executor/cuda/cuda_driver.cc:313] failed call to cuInit: UNKNOWN ERROR (-1)
2022-11-10 21:32:26.830736: I tensorflow/stream_executor/cuda/cuda_diagnostics.cc:156] kernel driver does not appear to be running on this host (f5005090f1e4): /proc/driver/nvidia/version does not exist
2022-11-10 21:32:26.830944: I tensorflow/core/platform/cpu_feature_guard.cc:143] Your CPU supports instructions that this TensorFlow binary was not compiled to use: AVX2 FMA
2022-11-10 21:32:26.838405: I tensorflow/core/platform/profile_utils/cpu_utils.cc:102] CPU Frequency: 2904010000 Hz
2022-11-10 21:32:26.839976: I tensorflow/compiler/xla/service/service.cc:168] XLA service 0x7f271c000b20 initialized for platform Host (this does not guarantee that XLA will be used). Devices:
2022-11-10 21:32:26.840017: I tensorflow/compiler/xla/service/service.cc:176]   StreamExecutor device (0): Host, Default Version
>> generate with decoder wise... beam size is None
Traceback (most recent call last):
  File "generate.py", line 52, in <module>
    mt = MusicTransformerDecoder(loader_path=load_path)
  File "/src/model.py", line 267, in __init__
    self.load_config_file(loader_path)
  File "/src/model.py", line 366, in load_config_file
    with open(config_path, 'r') as f:
FileNotFoundError: [Errno 2] No such file or directory: '/data/trained-models/ambient-musictransformer-model-2-june-3-2020-750-epochs-more-data/config.json'
PS D:\ambient-music-generation>

**Comment by mike-laws** [comment]
On windows in powershell I had to use

docker run -it -v 'D:\ambient-music-generation':/data --entrypoint python jimmywhitaker/music-transformer:0.1 generate.py --load_path=/data/trained-models/ambient-musictransformer-model-2-june-3-2020-750-epochs-more-data --inputs /data/samples/midi/1.mid --length=2048 --save_path=/data/generated-music/my-sample-song-1.mid

where the D:\ambient-music-generation is the absolute path to map to /data
